### ISSUE TITLE
Support sbt run

### ISSUE THREAD

**Issue by codepitbull** [vert-x3/vertx-scala.g8#2]
We should allow to run the Main-Verticle using the sbt-built-in run feature.

**Comment by blueberrynotblue** [comment]
@codepitbull hi, thanks to your great work. Btw, when will this project upgrade to 3.5.2, which reduced fat-jar size (I guess)?

**Comment by codepitbull** [comment]
Currently on business trip. I will update this weekend :)

**Comment by vamartinez** [comment]
@codepitbull are you working on this issue?
