### ISSUE TITLE
Reload on save

### ISSUE THREAD

**Issue by imetallica** [vert-x3/vertx-scala.g8#4]
Hi!

Is it possible to make it recompile the namespaces on save and reload the project?

**Comment by codepitbull** [comment]
Recompile is no problem, that is covered by sbt (see here https://alvinalexander.com/scala/sbt-how-to-compile-run-package-scala-project, the command you are looking for is ~compile).
What exactly do you mean with "reload the project"?

**Comment by imetallica** [comment]
@codepitbull I mean, when I save it restarts the verticle with new code running, so I can just start sbt once and be done with it.

**Comment by codepitbull** [comment]
That feature would be great but so far I didn't have the time to implement it.
I am also currently pretty occupied with this issue https://github.com/vert-x3/vertx-lang-scala/issues/72

If you have an idea on how to get reloading going: PRs are always welcome ;)
