### ISSUE TITLE
[info] pull access denied for frolvlad/alpine-oraclejdk8

### ISSUE THREAD

**Issue by megafarad** [vert-x3/vertx-scala.g8#6]
Running "docker" in the SBT console yields the following errror:

`pull access denied for frolvlad/alpine-oraclejdk8, repository does not exist or may require 'docker login': denied: requested access to the resource is denied`

It appears the image has been removed. Perhaps openjdk:8-alpine should be used instead?

**Comment by codepitbull** [comment]
Thanks for pointing out. I thought I had this already fixed.
I will take care of it.

**Comment by codepitbull** [comment]
I have updated the image to adoptopenjdk/openjdk8:latest and verifgied that it's working.
